

platform :ios, '18.0'


target 'EAM' do

  use_frameworks!

  pod 'EssentialFeedPOD', :git => 'git@github.com:denickman/EssentialFeedPOD.git'

  target 'EAMTests' do

  end

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['DEAD_CODE_STRIPPING'] = "YES"
  end
end






# hooks
# pre_install do |installer|
#   puts "pre_install" # write this text in terminal line
# end
#
# post_install do |installer|
#   puts "post_install" # write this text in terminal line
# end
#
# pre_integrate do |installer|
#   puts "pre_integrate" # write this text in terminal line
# end
#
# post_integrate do |installer|
#   puts "post_integrate" # write this text in terminal line
# end
